package constants

type AgentCategory int

const (
	MAX_AGENTS int = 64

	AGENT_CATEGORY_UNDEFINED AgentCategory = iota
	AGENT_CATEGORY_PLAYER
	AGENT_CATEGORY_FRIENDLY_MOB
	AGENT_CATEGORY_ENEMY_MOB
)
